name: Compiler Warnings

on: push

jobs:
  msvc:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost Test
        run: vcpkg --triplet x64-windows install boost-test

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CMAKE_GENERATOR: "Visual Studio 17 2022"
          CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        run: cmake -DSIGHTREAD_BUILD_TESTS=ON -DSIGHTREAD_ENABLE_WARNINGS=ON ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  windows-gcc:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost Test
        run: |
          $env:PATH = "C:\msys64\usr\bin;$env:PATH"
          vcpkg --triplet x64-mingw-static install boost-test

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CMAKE_GENERATOR: "MinGW Makefiles"
          CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        run: |
          $env:PATH = "C:\msys64\usr\bin;$env:PATH"
          cmake -DSIGHTREAD_BUILD_TESTS=ON -DSIGHTREAD_ENABLE_WARNINGS=ON -DVCPKG_TARGET_TRIPLET=x64-mingw-static ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  windows-clang:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost Test
        run: vcpkg --triplet x64-windows install boost-test

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          CMAKE_GENERATOR: "Visual Studio 17 2022"
          CMAKE_GENERATOR_TOOLSET: ClangCL
          CMAKE_TOOLCHAIN_FILE: C:/vcpkg/scripts/buildsystems/vcpkg.cmake
        run: cmake -DSIGHTREAD_BUILD_TESTS=ON -DSIGHTREAD_ENABLE_WARNINGS=ON ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  mac-gcc:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost 1.86.0
        run: |
          wget -O "$HOME/boost_1_86_0.tar.bz2" https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.bz2
          tar --bzip2 -xf "$HOME/boost_1_86_0.tar.bz2" -C "$HOME"
          cd "$HOME/boost_1_86_0"
          ./bootstrap.sh --with-libraries=test --prefix=.
          ./b2 toolset=gcc-14 install > /dev/null

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          BOOST_ROOT: ~/boost_1_86_0
          CXX: g++-14
        run: cmake -DSIGHTREAD_BUILD_TESTS=ON -DSIGHTREAD_ENABLE_WARNINGS=ON ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  apple-clang:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost
        run: brew install boost

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        run: cmake -DSIGHTREAD_BUILD_TESTS=ON -DSIGHTREAD_ENABLE_WARNINGS=ON ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  linux-gcc:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost 1.86.0
        run: |
          wget -O "$HOME/boost_1_86_0.tar.bz2" https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.bz2
          tar --bzip2 -xf "$HOME/boost_1_86_0.tar.bz2" -C "$HOME"
          cd "$HOME/boost_1_86_0"
          ./bootstrap.sh --with-libraries=test --prefix=.
          ./b2 toolset=gcc-14 install > /dev/null

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          BOOST_ROOT: ~/boost_1_86_0
          CXX: g++-14
        run: cmake -DSIGHTREAD_BUILD_TESTS=ON -DSIGHTREAD_ENABLE_WARNINGS=ON ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose

  linux-clang:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost 1.86.0
        run: |
          wget -O "$HOME/boost_1_86_0.tar.bz2" https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.bz2
          tar --bzip2 -xf "$HOME/boost_1_86_0.tar.bz2" -C "$HOME"
          cd "$HOME/boost_1_86_0"
          ./bootstrap.sh --with-libraries=test --prefix=.
          ./b2 toolset=clang-18 install > /dev/null

      - name: Make build directory
        run: mkdir build

      - name: Generate build files
        working-directory: build
        env:
          BOOST_ROOT: ~/boost_1_86_0
          CXX: clang++-18
        run: cmake -DSIGHTREAD_BUILD_TESTS=ON -DSIGHTREAD_ENABLE_WARNINGS=ON ..

      - name: Build
        working-directory: build
        run: cmake --build . --verbose
