name: Static Analysis

on: push

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Boost 1.86.0
        run: |
          wget -O "$HOME/boost_1_86_0.tar.bz2" https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.bz2
          tar --bzip2 -xf "$HOME/boost_1_86_0.tar.bz2" -C "$HOME"
          cd "$HOME/boost_1_86_0"
          ./bootstrap.sh --with-libraries=locale,test --prefix=.
          ./b2 toolset=gcc-14 install > /dev/null

      - name: Application files
        run: clang-tidy-18 src/sightread/*.cpp src/sightread/detail/*.cpp -- -Iinclude -Isrc -I$HOME/boost_1_86_0 -std=c++20

      - name: Test files
        run: clang-tidy-18 tests/sightread/*_unittest.cpp tests/sightread/detail/*_unittest.cpp -checks=-cppcoreguidelines-avoid-do-while,-cppcoreguidelines-avoid-magic-numbers,-cppcoreguidelines-avoid-non-const-global-variables,-cppcoreguidelines-macro-usage,-clang-analyzer-*,-readability-function-cognitive-complexity,-readability-magic-numbers -- -Iinclude -Isrc -Itests/sightread -I$HOME/boost_1_86_0 -std=c++20

  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format
        run: |
          clang-format-18 -i include/sightread/*.hpp src/sightread/*.cpp src/sightread/detail/*.cpp src/sightread/detail/*.hpp tests/sightread/*.cpp tests/sightread/*.hpp tests/sightread/detail/*.cpp
          git diff --color --exit-code
