name: Static Analysis

on: push

permissions: {}

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Boost 1.86.0
        run: |
          wget -O "$HOME/boost_1_86_0.tar.bz2" https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.bz2
          tar --bzip2 -xf "$HOME/boost_1_86_0.tar.bz2" -C "$HOME"
          cd "$HOME/boost_1_86_0"
          ./bootstrap.sh --with-libraries=locale,test --prefix=.
          ./b2 toolset=gcc-14 install > /dev/null

      - name: Install clang-tidy 22
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main"
          sudo apt-get update
          sudo apt-get install clang-tidy-22

      - name: Make build directory
        run: mkdir build

      - name: Generate compilation database
        working-directory: build
        env:
          BOOST_ROOT: ~/boost_1_86_0
          CXX: g++-14
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DSIGHTREAD_BUILD_TESTS=ON ..

      - name: Run clang-tidy
        run: run-clang-tidy-22 -p=build/ -hide-progress -quiet

  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install clang-format 22
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main"
          sudo apt-get update
          sudo apt-get install clang-format-22

      - name: Format
        run: |
          clang-format-22 -i include/sightread/*.hpp src/sightread/*.cpp src/sightread/detail/*.cpp src/sightread/detail/*.hpp tests/sightread/*.cpp tests/sightread/*.hpp tests/sightread/detail/*.cpp
          git diff --color --exit-code

  gersemi:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install gersemi
        run: pip install gersemi

      - name: Format
        run: |
          gersemi . --in-place --indent 2 --no-warn-about-unknown-commands
          git diff --color --exit-code
